### ISSUE TITLE
Incorrect values and not all information

### ISSUE THREAD

**Issue by ghost** [aperpen/clash-royale-client#2]
Hello! The client issues the wrong fields of the shopArenaPack. It is very large. Also in the client do not work top lists of players, getting information about the tournament. I would also like to see information about all the player's cards, his battles and many other information, for example, Draws and 2x2, Cards from tournaments, Maximum victories in tournaments. Also whether the nickname changed or not, the account's status, the current status (online / offline) and when the player last entered the game, how many the player changed the clan, the last fight played and a lot of other information, because the more it's the better. In the clans I would like to see a list of the player's battles yet.

Thank you for such a cool client and for his support.

**Comment by aperpen** [comment]
Hi!

- shopArenaPack value is which Supercell server sends, however I'm removing shop fields because Supercell asked some time ago to don't show it and the values now aren't 100% reliable.
- TopPlayers definition fixed in 58482dec888b6ae93185a6bac994ecd2eb1957a5 
- Tournaments command is disabled by now, I'll work on the new definition when I have free time.
- Extra info: 
   1. Player's cards, player battles, 2x2, current status, last game, how many times the player changed clan etc. aren't sent by the server (or at least I didn't find them)
   2. Name changed and tournaments card count added in 58482dec888b6ae93185a6bac994ecd2eb1957a5
   3. You can easily calculate draws doing `battles - (wins + losses)`
