### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by ghost** [aperpen/clash-royale-client#3]
What about the values of "Victories in the day of wars" and "Collected maps of the clan"? They were added to the player profile information. Also, the client does not have the value "Winning cards" (tournaments). And yet, is there a cycle of quests, can you find out what and how many chests in slots, how much will the royal chest and many other information be available? I'm already bored, probably with my requests, but still I want to know about it ...

UPD: Clans doesn't work.

**Comment by aperpen** [comment]
- Profile war fields, and how many chests in slots added in 0e5ce8d6f2512becda97f41252adbca20d9b85e6 :+1:
- What chests does the user have in slots, quest cycle etc. is not avaiable
- What do you mean with `how much will the royal chest`?
- Tournament cards field was already added yesterday in 58482dec888b6ae93185a6bac994ecd2eb1957a5:
![image](https://user-images.githubusercontent.com/24506783/39527483-c1ae7be2-4e21-11e8-9434-c7a453e0dfe1.png)
- Why clans don't work? Just tried clan command and works, please provide more details about the error, otherwise I won't be able to help.
